version: "2"
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 32181
      ZOOKEEPER_TICK_TIME: 2000
    network_mode: host
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: localhost:32181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    network_mode: host
#  rest-proxy:
#    image: confluent/rest-proxy
#    depends_on:
#      - zookeeper
#      - kafka
#      - schema-registry
#    ports:
#      - "8082:8082"
#    environment:
#      RP_ZOOKEEPER_CONNECT: "confluent:2181"
#      RP_SCHEMA_REGISTRY_URL: "http://confluent:8081"
#    network_mode: "host"
#  schema-registry:
#    image: confluent/schema-registry
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - "8081:8081"
#    environment:
#      SR_KAFKASTORE_CONNECTION_URL: "confluent:2181"